import { StyleSheet } from "@react-pdf/renderer";
import type { BrandingTokens } from "@/types/database";

export function createPdfStyles(branding: BrandingTokens) {
  const primary = branding.primaryColor;
  const ink = branding.secondaryColor;

  return StyleSheet.create({
    page: {
      paddingTop: 48,
      paddingBottom: 56,
      paddingHorizontal: 40,
      fontFamily: branding.fontFamily,
      fontSize: 10,
      color: ink,
      backgroundColor: branding.backgroundColor,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 22,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
      paddingRight: 12,
    },
    headerRight: {
      backgroundColor: "#ffffff",
      borderRadius: 6,
      borderWidth: 1,
      borderColor: "#e5e0da",
      paddingVertical: 10,
      paddingHorizontal: 12,
      minWidth: 128,
    },
    logoBox: {
      width: 42,
      height: 42,
      backgroundColor: primary,
      borderRadius: 6,
      alignItems: "center",
      justifyContent: "center",
    },
    logoText: {
      color: "#ffffff",
      fontSize: 14,
      fontWeight: "bold",
    },
    agencyName: {
      fontSize: 13,
      fontWeight: "bold",
      color: primary,
      maxWidth: 280,
    },
    docType: {
      fontSize: 9,
      color: "#666",
      marginTop: 2,
    },
    metaLabel: {
      fontSize: 7,
      color: "#999",
      textTransform: "uppercase",
      letterSpacing: 0.6,
      marginBottom: 1,
    },
    metaValue: {
      fontSize: 9,
      color: ink,
      fontWeight: "bold",
      marginBottom: 5,
    },
    titleBlock: {
      marginBottom: 14,
      paddingBottom: 12,
      borderBottomWidth: 2,
      borderBottomColor: primary,
    },
    title: {
      fontSize: 22,
      fontWeight: "bold",
      color: ink,
      marginBottom: 4,
      letterSpacing: -0.3,
    },
    subtitle: {
      fontSize: 10,
      color: "#555",
      lineHeight: 1.45,
    },
    messageBox: {
      marginBottom: 16,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: "#ffffff",
      borderRadius: 6,
      borderLeftWidth: 4,
      borderLeftColor: primary,
      borderWidth: 1,
      borderColor: "#e5e0da",
    },
    messageLabel: {
      fontSize: 8,
      fontWeight: "bold",
      color: primary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    messageText: {
      fontSize: 10,
      lineHeight: 1.55,
      color: "#333",
    },
    infoGrid: {
      flexDirection: "row",
      gap: 12,
      marginBottom: 20,
    },
    infoCard: {
      flex: 1,
      backgroundColor: "#ffffff",
      borderRadius: 6,
      borderWidth: 1,
      borderColor: "#e5e0da",
      padding: 12,
    },
    infoCardLabel: {
      fontSize: 7,
      fontWeight: "bold",
      color: "#999",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 8,
    },
    infoLine: {
      fontSize: 9,
      color: "#444",
      marginBottom: 3,
      lineHeight: 1.4,
    },
    infoLineStrong: {
      fontSize: 11,
      fontWeight: "bold",
      color: ink,
      marginBottom: 4,
    },
    tableHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 6,
      paddingHorizontal: 4,
      marginBottom: 4,
      borderBottomWidth: 1,
      borderBottomColor: primary,
    },
    tableHeaderText: {
      fontSize: 8,
      fontWeight: "bold",
      color: primary,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    phaseTitle: {
      fontSize: 11,
      fontWeight: "bold",
      color: primary,
      marginTop: 14,
      marginBottom: 8,
    },
    groupRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      paddingVertical: 8,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: "#eeeae5",
    },
    groupTitle: {
      fontSize: 9.5,
      fontWeight: "bold",
      color: ink,
      marginBottom: 2,
    },
    groupDesc: {
      fontSize: 8,
      color: "#666",
      lineHeight: 1.35,
      maxWidth: 380,
    },
    amount: {
      fontSize: 9.5,
      fontWeight: "bold",
      color: primary,
      width: 76,
      textAlign: "right",
    },
    totalsBox: {
      marginTop: 18,
      padding: 14,
      backgroundColor: "#ffffff",
      borderRadius: 6,
      borderWidth: 1,
      borderColor: "#e5e0da",
    },
    totalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 4,
      fontSize: 9,
      color: "#444",
    },
    totalDivider: {
      borderTopWidth: 1,
      borderTopColor: "#e5e0da",
      marginVertical: 8,
      paddingTop: 8,
    },
    grandTotal: {
      fontSize: 12,
      fontWeight: "bold",
      color: primary,
    },
    sectionBlock: {
      marginTop: 14,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: "#e5e0da",
    },
    sectionLabel: {
      fontSize: 9,
      fontWeight: "bold",
      color: primary,
      marginBottom: 5,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    bodyText: {
      fontSize: 9,
      lineHeight: 1.5,
      color: "#444",
    },
    footer: {
      position: "absolute",
      bottom: 24,
      left: 40,
      right: 40,
      fontSize: 7,
      color: "#999",
      textAlign: "center",
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: "#ddd",
    },
  });
}
